### ISSUE TITLE
Any idea for hz-offheap support for 3.4+

### ISSUE THREAD

**Issue by bwzhang2011** [jankotek/mapdb-hz-offheap#1]
jankotek, from github we got to know that mapdb provided some integration for hazelcast off-heap support. but it's unlucky that it would only support low version of hazelcast where it changed a lot since hazelcast 3.4+.  after several days working I tried to make it work but it could not pass your bench mark test. so would you mind spare sometime to give it a try to integrated with hazelcast new version. and what's more, new hazelcast has brought in new title like native memory to support offheap.

**Comment by bwzhang2011** [comment]
@jankotek, would you mind leaving me some advice on such ?

**Comment by bwzhang2011** [comment]
@jankotek, please give me some advice on how to enable such support for 3.4 offheap support if could be done so ?

**Comment by oallouch** [comment]
Looks dead.

**Comment by jankotek** [comment]
@bwzhang2011 @oalouch Hi, this project is dead. 3.4+ is more complex, I can not use agent injection.

I might fork Hazelcast in future to add mapdb support. Bot for next 3+ moths stable 2.0 release is priority.

**Comment by oallouch** [comment]
I can understand that they don't want to ease an open source version of their best paid feature.

**Comment by jankotek** [comment]
Not really! 

Agent injection is bloody hack. Plus 3.3 is older than this plugin and problems are already there.

**Comment by bwzhang2011** [comment]
@jankotek , hz3.4+ brought in the hi-density more design which is similar to the off-heap support but could be implemented from mapdb. here comes some testing code that I need your help (if you have free time and just paid a look at)
1. OffHeapDataRef:

@SuppressWarnings("serial")
public class OffHeapDataRef implements DataRef, Serializable {

```
private final Data m_data;

private OffHeapDataRef(final Data data) {
    this.m_data = data;
}

public static DataRef createDataRef(Data data) {
    return new OffHeapDataRef(data);
}

@Override
public int heapCost() {
    return this.m_data.getHeapCost();
}

@Override
public int size() {
    return this.m_data.dataSize();
}

public Data getData() {
    return this.m_data;
}
```

}
1. OffHeapStorage
   public class OffHeapStorage implements Storage<DataRef> {
   private static final Logger LOGGER = LoggerFactory.getLogger(OffHeapStorage.class);
   
   private final DB m_store;
   
   private final HTreeMap<Integer, DataRef> m_map;
   
   public OffHeapStorage(boolean disableTrans, boolean disableCache, boolean enableAsyncWrite, int writeDelay, boolean enableCompress,
           boolean enablePwd, String password, String dataRefName) {
       this.m_store = 
               DBMapHelper.createMemoryDB(disableTrans, disableCache, enableAsyncWrite, writeDelay, enableCompress, enablePwd,password);
       this.m_map = DBMapHelper.createDataRefMap(this.m_store, dataRefName);
   }
   
   @Override
   public void destroy() {
       LOGGER.debug("destroy<{}>", this.m_store);
       m_store.close();
   }
   
   @Override
   public Data get(int hash, DataRef ref) {  
       return ((OffHeapDataRef) ref).getData();
   }
   
   @Override
   public DataRef put(int hash, Data data) {  
       DataRef dref = OffHeapDataRef.createDataRef(data);
       m_map.put(hash, dref);
       return dref;
   }
   
   @Override
   public void remove(int hash, DataRef ref) {  
       m_map.remove(hash);
   }

}
1. OffHeapNodeExtension
   public class OffHeapNodeExtension extends DefaultNodeExtension {
   private static final Logger LOGGER = LoggerFactory.getLogger(OffHeapNodeExtension.class);
   
   private boolean disableTrans;
   
   private boolean disableCache;
   
   private boolean enableAsyncWrite;
   
   private int writeDelay;
   
   private boolean enableCompress;
   
   private boolean enablePwd;
   
   private String password;
   
   private String dataRefName;
   
   @Override
   public void afterStart(Node node) {
       super.afterStart(node);
       Config config = node.getConfig();
   
   ```
   String _disableTrans = config.getProperty("mapdb.disableTrans");
   this.disableTrans = CommonHelper.checkIsEmpty(_disableTrans) ? true: Boolean.valueOf(_disableTrans);        
   String _disableCache = config.getProperty("mapdb.disableCache");
   this.disableCache = CommonHelper.checkIsEmpty(_disableCache) ? true : Boolean.valueOf(_disableCache);       
   String _enableAsyncWrite = config.getProperty("mapdb.enableAsyncWrite");
   this.enableAsyncWrite = CommonHelper.checkIsEmpty(_enableAsyncWrite) ? false : Boolean.valueOf(_enableAsyncWrite);
   
   this.writeDelay = MathHelper.str2Int(config.getProperty("mapdb.writeDelay"));
   this.enableCompress = Boolean.valueOf(config.getProperty("mapdb.compressEnable"));
   this.enablePwd = Boolean.valueOf(config.getProperty("mapdb.enablePwd"));
   this.password = config.getProperty("mapdb.password");
   this.dataRefName = config.getProperty("mapdb.dataRefName");
   
   LOGGER.info("OffHeap MapDB configuration:<{},{},{},{},{},{},{},{}>", this.disableTrans, this.disableCache, this.enableAsyncWrite,
                                                                        this.writeDelay, this.enableCompress, this.enablePwd, 
                                                                        this.password, this.dataRefName);
   ```
   
   }
   
   @Override
   public Storage<DataRef> getNativeDataStorage() {
       return new OffHeapStorage(this.disableTrans, this.disableCache, this.enableAsyncWrite, this.writeDelay, this.enableCompress,
                                 this.enablePwd, this.password, this.dataRefName);
   }

}

4.DBMapHelper
public final class DBMapHelper {
    private static final String DEFAULT_DATA_REF_NAME = "hz_offheap";

```
public static DB createMemoryDB(boolean disableTrans, boolean disableCache, boolean enableAsyncWrite, int writeDelay,
        boolean enableCompress, boolean enablePwd, String password) {
    DBMaker dbMaker = DBMaker.newMemoryDirectDB();

    if (disableTrans) {
        dbMaker.transactionDisable();
    }

    if (disableCache) {
        dbMaker.cacheDisable();
    }

    if (enableAsyncWrite) {
        dbMaker.asyncWriteEnable();

        if (writeDelay > 0) {
            dbMaker.asyncWriteFlushDelay(writeDelay);
        }
    }

    if (enableCompress) {
        dbMaker.compressionEnable();
    }

    if (enablePwd && CommonHelper.checkIsNotEmpty(password)) {
        dbMaker.encryptionEnable(password);
    }

    return dbMaker.make();
}

public static HTreeMap<Integer, DataRef> createDataRefMap(boolean disableTrans, boolean disableCache, boolean enableAsyncWrite,
        int writeDelay, boolean enableCompress, boolean enablePwd, String password, String dataRefName) {
    DB memoryDB = createMemoryDB(disableTrans, disableCache, enableAsyncWrite, writeDelay, enableCompress, enablePwd, password);

    return createDataRefMap(memoryDB, dataRefName);
}

public static HTreeMap<Integer, DataRef> createDataRefMap(DB memoryDB, String dataRefName) {
    dataRefName = CommonHelper.checkIsEmpty(dataRefName) ? DEFAULT_DATA_REF_NAME : dataRefName;

    return memoryDB.createHashMap(dataRefName).keySerializer(Serializer.INTEGER).valueSerializer(new MapDBDataRefSerializer()).make();
}

@SuppressWarnings("serial")
private static class MapDBDataSerializer extends Serializer<Data> implements java.io.Serializable {

    @Override
    public Data deserialize(DataInput dataInput, int i) throws IOException {
        int type = dataInput.readInt();
        byte[] buf = new byte[dataInput.readInt()];
        dataInput.readFully(buf);
        DefaultData d = new DefaultData(type, buf);
        d.setPartitionHash(dataInput.readInt());
        return d;
    }

    @Override
    public void serialize(DataOutput dataOutput, Data data) throws IOException {
        dataOutput.writeInt(data.getType());
        dataOutput.writeInt(data.dataSize());
        dataOutput.write(data.getData());
        dataOutput.writeInt(data.getPartitionHash());
    }

}

@SuppressWarnings("serial")
private static class MapDBDataRefSerializer extends Serializer<DataRef> implements java.io.Serializable {

    public static final MapDBDataSerializer ds = new MapDBDataSerializer();

    @Override
    public DataRef deserialize(DataInput dataInput, int i) throws IOException {
        Data data = ds.deserialize(dataInput, -1);
        return OffHeapDataRef.createDataRef(data);
    }

    @Override
    public void serialize(DataOutput dataOutput, DataRef dataRef) throws IOException {
        OffHeapDataRef o_dataRef = (OffHeapDataRef) dataRef;
        ds.serialize(dataOutput, o_dataRef.getData());
    }

}
```

}

**Comment by bwzhang2011** [comment]
enable the META-INF service to load the extension:
com.hazelcast.instance.NodeExtension= com.xx.xx.offheap.OffHeapNodeExtension

**Comment by bwzhang2011** [comment]
@jankotek , no matter what your plan for mapdb support for offheap towards hz3.4+, we appreciated of your great work and look forward to that forthcoming not long in the future.

**Comment by jankotek** [comment]
I will put this on my TODO list and have a look in couple of weeks. Very busy right now (sorry)

**Comment by bwzhang2011** [comment]
@jankotek , thanks for feed back. we're glad to see that such would be the choice in your list as your plan in the future.

**Comment by bwzhang2011** [comment]
@jankotek, any update with such issue. the reason care about this is hazelast is somewhat the active project for IMDG solution compared with gridgain (though very strong but not more projects integration) and mapdb could be considered as the simplest but very helpful solution not only for off-heap but also provides other structure to be as the storage solution.so it would be very nice to make it further as you described in the wiki. as your suggestion I have done some integration work but the performance is not very good for write speed and I don't know whether it could be scale to satisfy very large data set e.g about 10GB or more.so we need your help and great work.

**Comment by jankotek** [comment]
Still very busy, maybe two months

**Comment by bwzhang2011** [comment]
@jankotek, thanks for view. at least for me I could not be waiting so long that I decided to continue your integration and make it run under mapdb2.0 snapshot and everything goes fine but I don't know how to solve the bottleneck and improve the write speed and in short test, it still throws the out of memory even if I enable the off-heap configuration. so we hope if you don't mind, some test codes would be much appreciated.

**Comment by bwzhang2011** [comment]
@jankotek, any update with such issue. maybe you just spare sometime for a small step but a big one for us to enjoy the  offheap. so looking forward to your code even with the test one I will grasp it into my project and test it in my environment.

**Comment by prabhuish** [comment]
@jankotek, Appreciate your effort of creating this library. It will be great helpful if we get some update about this implementation. Can you please share few info.

**Comment by jankotek** [comment]
Right now based on my priorities and TODO list, it will be about two months before new version is out.

**Comment by prabhuish** [comment]
Thanks @jankotek.

**Comment by jankotek** [comment]
@bwzhang2011  @oallouch  @prabhuish There is new release which targets HZ 3.5.1 and uses MapDB 2.0 beta. I decided to revive this project and support it in future. Checkout updated readme

**Comment by prabhuish** [comment]
wow..that is awesome..will have a look @jankotek ..Thank you..

**Comment by oallouch** [comment]
That would definitely rock !!!

**Comment by bwzhang2011** [comment]
@jankotek, thanks a lot for following such project. as your commented, looking forward to more close integration with mapdb and hazelcast. by the way, when i run benchmark in eclipse, it's easy to generate the outofmemory exception and it's strange that the jvm parameter did no work while the item  reached some higher number (maybe 10 million items) and it seemed it stopped inserting and everything became very slow. so would you mind leaving more message that such test should be started in a single process with agent support or could be run under IDE.
